### ISSUE TITLE
linking fails, more recent SDL2 versions expect shell32.lib

### ISSUE THREAD

**Issue by a-n-d-a-i** [Costava/sdl2-draw-demo#2]
I was able to get this to build with SDL 2.28.5 by adding `shell32.lib`.
(Not sure in which SDL2 version that became a requirement.)
Otherwise, build fails with:
```
SDL2main.lib(SDL_windows_main.obj) : error LNK2019: unresolved external symbol __imp_CommandLineToArgvW referenced in function main_getcmdline
```
